version: 2.1
orbs:
  ruby: circleci/ruby@1.0

jobs:
  test:
    docker:
      - image: circleci/ruby:2.7
    executor: ruby/default
    steps:
      - checkout
      - ruby/install-deps
      - run: bundle exec rubocop -a
      - run: bundle exec rake spec

workflows:
  validation:
    jobs:
      - test
