# frozen_string_literal: true

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kohi/v1/coffee.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file('kohi/v1/coffee.proto', syntax: :proto3) do
    add_message 'kohi.v1.Bean' do
      optional :variety, :enum, 1, 'kohi.v1.Bean.Variety'
      optional :amount, :float, 2
    end
    add_enum 'kohi.v1.Bean.Variety' do
      value :VARIETY_UNSPECIFIED, 0
      value :VARIETY_ROBUSTA, 1
      value :VARIETY_ARABICA, 2
    end
    add_message 'kohi.v1.Milk' do
      optional :variety, :enum, 1, 'kohi.v1.Milk.Variety'
      optional :amount, :float, 2
    end
    add_enum 'kohi.v1.Milk.Variety' do
      value :VARIETY_UNSPECIFIED, 0
      value :VARIETY_FULL_CREAM, 1
      value :VARIETY_SOY, 2
      value :VARIETY_ALMOND, 3
      value :VARIETY_RICE, 4
    end
    add_message 'kohi.v1.Coffee' do
      optional :beans, :message, 1, 'kohi.v1.Bean'
      optional :water, :float, 2
      optional :milk, :message, 3, 'kohi.v1.Milk'
      optional :ice, :bool, 4
    end
  end
end

module Kohi
  module V1
    Bean = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('kohi.v1.Bean').msgclass
    Bean::Variety = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('kohi.v1.Bean.Variety').enummodule
    Milk = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('kohi.v1.Milk').msgclass
    Milk::Variety = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('kohi.v1.Milk.Variety').enummodule
    Coffee = ::Google::Protobuf::DescriptorPool.generated_pool.lookup('kohi.v1.Coffee').msgclass
  end
end
